apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml
  - ingress.yaml

patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: argocd
    target:
      kind: ClusterRoleBinding
  - path: configmap-argocd-cmd-params-cm-patch.yaml
  - path: configmap-argocd-cm-patch.yaml
  - path: configmap-argocd-rbac-cm-patch.yaml
  - path: secret-argocd-secret-patch.yaml
