apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  template:
    spec:
      containers:
        - name: keycloak
          # Use start-dev to run in dev mode
          args: ["start", "--import-realm"]
          env:
            - name: KC_HOSTNAME
              value: "your.keycloak.instance.url"
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "YourSuperSecretAdminUsername"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "YourSuperSecretAdminP455w0rd"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_HEALTH_ENABLED
              value: "true"
            # Enable HTTP listener because of ingress
            - name: KC_HTTP_ENABLED
              value: "true"
          volumeMounts:
          - name: configmap-realm-volume
            mountPath: /opt/keycloak/data/import
      volumes:
        - name: configmap-realm-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: configmap-realm
