apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak
resources:
  - https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/refs/heads/main/kubernetes/keycloak.yaml
  - ingress.yaml
  # Create file on your own: export realm via Keycloak UI then
  # kubectl create configmap configmap-realm.yaml --from-file=realm-export.json --dry-run=client -o yaml > configmap-realm.yaml
  - configmap-realm.yaml

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
