---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-injection: enabled
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    istio-injection: enabled
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-env
  labels:
    istio-injection: enabled
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: uat-env
  labels:
    istio-injection: enabled
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-env
  labels:
    istio-injection: enabled
spec: {}
