apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodejs-colorizedapp.fullname" . }}-d1
  labels:
    {{- include "nodejs-colorizedapp.labels" . | nindent 4 }}
    {{- include "nodejs-colorizedapp.versionLabel" (list . .Values.deployments.d1.image.tag) | nindent 4 }}
    {{- include "nodejs-colorizedapp.selectorLabels" (list . "d1") | nindent 4 }}
spec:
  revisionHistoryLimit: 10
  {{- if not .Values.deployments.d1.autoscaling.enabled }}
  replicas: {{ .Values.deployments.d1.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nodejs-colorizedapp.selectorLabels" (list . "d1") | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployments.d1.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nodejs-colorizedapp.labels" . | nindent 8 }}
        {{- include "nodejs-colorizedapp.versionLabel" (list . .Values.deployments.d1.image.tag) | nindent 8 }}
        {{- include "nodejs-colorizedapp.selectorLabels" (list . "d1") | nindent 8 }}
        {{- with .Values.deployments.d1.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ ne .Values.deployments.d1.serviceAccount.automount false }}
      {{- with .Values.deployments.d1.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nodejs-colorizedapp.serviceAccountName-d1" . }}
      securityContext:
        {{- toYaml .Values.deployments.d1.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deployments.d1.securityContext | nindent 12 }}
          image: "{{ .Values.deployments.d1.image.repository }}:{{ .Values.deployments.d1.image.tag }}"
          imagePullPolicy: {{ .Values.deployments.d1.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{ .Values.deployments.d1.livenessProbe | toYaml | indent 12 | trim }}
          readinessProbe:
            {{ .Values.deployments.d1.readinessProbe | toYaml | indent 12 | trim }}
          resources:
            {{- toYaml .Values.deployments.d1.resources | nindent 12 }}
          {{- with .Values.deployments.d1.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- range $k, $v := .Values.deployments.d1.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
      {{- with .Values.deployments.d1.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployments.d1.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployments.d1.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployments.d1.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
