apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "nodejs-colorizedapp.fullname" . }}
  labels:
    {{- include "nodejs-colorizedapp.labels" . | nindent 4 }}
spec:
  host: nodejs-colorizedapp
  subsets:
    - name: d1
      labels:
        {{- include "nodejs-colorizedapp.labels" . | nindent 8 }}
        {{- include "nodejs-colorizedapp.selectorLabels" (list . "d1" .Values.deployments.d1.appVersion) | nindent 8 }}
    - name: d2
      labels:
        {{- include "nodejs-colorizedapp.labels" . | nindent 8 }}
        {{- include "nodejs-colorizedapp.selectorLabels" (list . "d2" .Values.deployments.d2.appVersion) | nindent 8 }}
