{{- $top := . -}}
{{- range $deployment := .Values.deployments -}}
{{- if $deployment.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ include "nodejs-colorizedapp.fullname" . }}-{{ $deployment }}"
  labels:
    {{- include "nodejs-colorizedapp.labels" . | nindent 4 }}
    {{- include "nodejs-colorizedapp.selectorLabels" (list . $deployment) }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ include "nodejs-colorizedapp.fullname" $ }}-{{ $deployment }}"
  minReplicas: {{ $deployment.autoscaling.minReplicas }}
  maxReplicas: {{ $deployment.autoscaling.maxReplicas }}
  metrics:
    {{- if $deployment.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $deployment.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $deployment.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $deployment.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
