{{- $top := . -}}
{{- range $deployment := .Values.deployments -}}
{{- if $deployment.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "nodejs-colorizedapp.fullname" $ }}-{{ $deployment }}"
  labels:
    {{- include "nodejs-colorizedapp.labels" . | nindent 4 }}
    {{- include "nodejs-colorizedapp.selectorLabels" (list . $deployment $deployment.appVersion) }}
  {{- with $deployment.serviceAccount.annotations }}
  annotations:
    {{- toYaml $ | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $deployment.serviceAccount.automount }}
{{- end }}
{{- end }}
