apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "nodejs-colorizedapp.fullname" . }}
  labels:
    {{- include "nodejs-colorizedapp.labels" . | nindent 4 }}
spec:
  hosts:
    - "{{ include "nodejs-colorizedapp.fullname" . }}-{{ .Release.Namespace }}.*"
  gateways:
    - mesh
  http:
    - name: "default-splitting"
      route:
        - destination:
            host: {{ include "nodejs-colorizedapp.fullname" . }}
            port: 
              number: {{ .Values.service.port }}
            subset: d1
          weight: {{ include "nodejs-colorizedapp.trafficWeight" (list . "d1") }}
        - destination:
            host: {{ include "nodejs-colorizedapp.fullname" . }}
            port: 
              number: {{ .Values.service.port }}
            subset: d2
          weight: {{ include "nodejs-colorizedapp.trafficWeight" (list . "d2") }}
