name: CD build
run-name: CD job triggered by ${{ github.triggering_actor }} for ${{ github.ref_name }}
on: [workflow_dispatch]

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/ci.yaml
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to specific branch or commit
        uses: actions/checkout@v4

      - name: Create image tag
        id: customvars
        run: echo "image_tag=${GITHUB_REF_NAME//\//_}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Check outputs
        run: echo ${{ steps.customvars.outputs.image_tag }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          # Global variable in GH
          login-server: ${{ vars.ACR_ADDRESS }}
          # Secrets in GH
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASS }}

      - name: Build and push container to Azure Container Registry
        run: |
          docker build . -t ${{ vars.ACR_ADDRESS }}/nodejs-colorizedapp:${{ steps.customvars.outputs.image_tag }}
          docker push ${{ vars.ACR_ADDRESS }}/nodejs-colorizedapp:${{ steps.customvars.outputs.image_tag }}
