name: CD build
run-name: CD job triggered by ${{ github.triggering_actor }} on ${{ github.ref_name }}
on: [workflow_dispatch]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  call-ci-workflow:
    uses: ./.github/workflows/ci.yaml
    needs: checkout

  call-security-scans-scm-workflow:
    uses: ./.github/workflows/security-scans-scm.yaml
    needs: call-ci-workflow

  build-image:
    needs: call-security-scans-scm-workflow
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.customvars.outputs.image_tag }}
    steps:
      - name: Create image tag
        id: customvars
        run: echo "image_tag=${GITHUB_REF_NAME//\//_}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Check outputs
        run: echo ${{ steps.customvars.outputs.image_tag }}

      - name: Build an image from Dockerfile
        run: |
          docker build . -t ${{ vars.ACR_ADDRESS }}/nodejs-colorizedapp:${{ steps.customvars.outputs.image_tag }}

  call-security-scans-container-workflow:
    uses: ./.github/workflows/security-scans-container.yaml
    with:
      pull_image: false
      image_tag: ${{ vars.ACR_ADDRESS }}/nodejs-colorizedapp:${{ needs.build-image.outputs.image_tag }}
    needs: build-image

  push-image:
    needs: call-security-scans-container-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          # Global variable in GH
          login-server: ${{ vars.ACR_ADDRESS }}
          # Secrets in GH
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASS }}

      - name: Push image to Azure Container Registry
        run: |
          docker push ${{ vars.ACR_ADDRESS }}/nodejs-colorizedapp:${{ needs.build-image.outputs.image_tag }}
