name: CI build
run-name: CI job triggered by ${{ github.event_name }} to ${{ github.ref_name }}
on:
  push:
  workflow_call:

permissions:
  actions: read
  contents: read
  security-events: write
  issues: write
  statuses: write
  checks: write
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run linter
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"
      - run: npm ci
      - run: ./node_modules/.bin/eslint src/ tests/

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Run unit tests
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
