name: CI build
run-name: CI job triggered by ${{ github.event_name }} for ${{ github.ref_name }}
on:
  push:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  issue_comment:                                     
    types: [created, edited, deleted]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  long_ci:
    if: contains(github.event.comment.body, '/rerun') ||
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run linter
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - run: npm ci
      - run: ./node_modules/.bin/eslint src/ tests/

      - name: Run SCA scan
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - run: npm ci
      - run: ./node_modules/.bin/retire -v

      - name: Run secrets-leak scan
        uses: trufflesecurity/trufflehog@v3.66.3
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --only-verified

      - name: SAST scan
        uses: bearer/bearer-action@v2
        continue-on-error: true
        with:
          format: sarif
          output: results.sarif

      - name: Upload SAST scan report
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: SAST

      - name: Run unit tests
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  short_ci:
    if: github.event_name != 'pull_request' && github.event_name != 'issue_comment'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run linter
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - run: npm ci
      - run: ./node_modules/.bin/eslint src/ tests/

      - name: Run unit tests
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

