name: CI job for nodejs-colorizedapp
run-name: CI job triggered by ${{ github.event_name }} to ${{ github.ref_name }}
on: [push, pull_request]
jobs: 
  normal_ci:
    permissions:
      contents: read
      packages: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use linter
        uses: stefanoeb/eslint-action@1.0.2

      - name: Run unit tests
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

