name: CI build for PR
run-name: CI job triggered by ${{ github.event_name }} on ${{ github.ref_name }}
on:
  pull_request:

permissions:
  actions: read
  contents: read
  security-events: write
  issues: write
  statuses: write
  checks: write
  pull-requests: write

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/ci.yaml
    with:
      branch: ${{ needs.checkout.outputs.head_ref }}

  call-security-scans-scm-workflow:
    uses: ./.github/workflows/security-scans-scm.yaml
    with:
      branch: ${{ needs.checkout.outputs.head_ref }}
    needs: call-ci-workflow

  update-pr:
    if: always()
    needs: [call-ci-workflow, call-security-scans-scm-workflow]
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to PR
        uses: actions/github-script@v7
        id: workflowstatus
        with:
          script: |
            const name = '${{ github.workflow }}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const workflowResult = (
              '${{ needs.call-ci-workflow.result }}' === 'success' &&
              '${{ needs.call-security-scans-scm-workflow.result }}' === 'success'
            ) ? 'success' : 'failure';
            const body = `${name}: ${workflowResult === 'success' ? 'succeeded ✅' : 'failed ❌'}\n${url}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

            core.setOutput('workflowresult', workflowResult);

      - name: Set latest commit status as ${{ steps.workflowstatus.outputs.workflowresult }}
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ needs.checkout.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ steps.workflowstatus.outputs.workflowresult }}
