name: Periodical security analysis
run-name: PSA job triggered by ${{ github.event_name }} for ${{ github.ref_name }}
on:
  schedule:
    - cron: '37 21 * * 6'
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Not neded to specify branch: 
          # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
          fetch-depth: 0

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Get latest release for nodejs-colorizedapp
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@master
        continue-on-error: true
        with:
          repository: ${{ github.repository }}

      - name: Generate image tag if latest release found
        if: ${{ steps.latest_release.outputs.release }}
        run: |
          echo "TAG_TO_PULL=${{ steps.latest_release.outputs.release }}" >> "$GITHUB_ENV"

      - name: Generate image tag if no releases found
        if: ${{ ! steps.latest_release.outputs.release }}
        id: generated_tag
        run: |
          echo "TAG_TO_PULL=${GITHUB_REF_NAME//\//_}-$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: SCA scan (nodejs packages)
        uses: actions/setup-node@v3
        id: sca_nodejs
        with:
          node-version: "lts/jod"
      - run: npm ci
      # In case of vulnerabilities command will return non zero exit-code
      - run: npm audit --audit-level=moderate

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis & results to GitHub Security tab
        id: codeql
        uses: github/codeql-action/analyze@v3

      - name: SAST scan
        uses: bearer/bearer-action@v2
        id: sast
        with:
          format: sarif
          output: bearer-results.sarif
          exit-code: 0

      - name: Upload SAST scan results to GitHub Security tab
        if: ${{ always() }}
        # Ignore empty report
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bearer-results.sarif
          category: SAST

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          # Global variable in GH
          registry: ${{ vars.ACR_ADDRESS }}
          # Secrets in GH
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASS }}

      - name: Pull image from Azure Container Registry
        run: |
          docker pull ${{ vars.ACR_ADDRESS }}/nodejs-colorizedapp:${{ env.TAG_TO_PULL }}

      - name: SCA scan (Docker image)
        uses: aquasecurity/trivy-action@master
        id: sca_docker
        with:
          image-ref: '${{ vars.ACR_ADDRESS }}/nodejs-colorizedapp:${{ env.TAG_TO_PULL }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          scanners: 'vuln,secret,config'

      - name: Upload SCA scan results to GitHub Security tab
        if: ${{ always() }}
        # Ignore empty report
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          category: SCA

      # Catch previous failures and set status to FAILED
      - name: Set workflow status conditionally
        if: ${{ always() }}
        run: |
          #!/usr/bin/env bash

          set -euo pipefail

          echo 'Checking result of CodeQL analysis...'
          if [[ "${{ steps.codeql.outcome }}" == 'success' ]]; then
            echo 'CodeQL analysis status is success'
          else
            echo 'CodeQL analysis failed'
            exit 1
          fi
          echo 'Checking result of SAST analysis...'
          if [[ "${{ steps.sast.outcome }}" == 'success' ]]; then
            echo 'SAST analysis status is success'
          else
            echo 'SAST analysis failed'
            exit 1
          fi
          echo 'Checking SCA (Docker) sarif report against critical severities...'
          if [[ ! -f trivy-results.sarif ]]; then
            echo 'File trivy-results.sarif not found, failing build!'
            exit 1
          fi
          if grep 'Severity: critical' 'trivy-results.sarif' -ivqz; then
            echo 'No vulnerabilities with severity critical found'
          else
            echo 'At least one vulnerability with severity critical found, failing build!'
            exit 1
          fi
          echo 'Checking SCA (Docker) sarif report against high severities...'
          if  grep 'Severity: high' 'trivy-results.sarif' -ivqz; then
            echo 'No vulnerabilities with severity high found'
          else
            echo 'At least one vulnerability with severity high found, failing build!'
            exit 1
          fi
