name: Release build
run-name: Release job triggered by ${{ github.event_name }} to ${{ github.ref_name }}
on:
  push:
    branches: ["release/*"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
