name: Security scans on SCM
run-name: SSSCM job triggered by ${{ github.event_name }} on ${{ github.ref_name }}
on:
  workflow_call:
    inputs:
      branch:
        description: 'A custom branch to checkout'
        default: 'master'
        required: false
        type: string

jobs:
  security_scans_scm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository - custom branch
        if: ${{ inputs.branch }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Checkout repository
        if: ${{ ! inputs.branch }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: SCA scan (nodejs packages)
        uses: actions/setup-node@v3
        with:
          node-version: "lts"
      - run: npm ci
      - run: npm audit --audit-level=moderate

      - name: Run secrets-leak scan
        uses: trufflesecurity/trufflehog@v3.66.3
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --only-verified

      - name: SAST scan
        uses: bearer/bearer-action@v2
        id: sast
        with:
          format: sarif
          output: bearer-results.sarif
          exit-code: 0

      - name: Upload SAST scan results to GitHub Security tab
        if: ${{ always() }}
        # Ignore empty report
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bearer-results.sarif
          category: SAST

      - name: CM Terraform scan
        uses: bridgecrewio/checkov-action@v12
        with:
          config_file: checkov-terraform.yaml
          output_format: cli,sarif
          output_file_path: console,checkov-terraform-results.sarif

      - name: Upload CM Terraform scan results to GitHub Security tab
        if: ${{ always() }}
        # Ignore empty report
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-terraform-results.sarif
          category: CM/Terraform

      - name: CM Dockerfile scan
        uses: bridgecrewio/checkov-action@v12
        with:
          config_file: checkov-dockerfile.yaml
          output_format: cli,sarif
          output_file_path: console,checkov-dockerfile-results.sarif

      - name: Upload CM Dockerfile scan results to GitHub Security tab
        if: ${{ always() }}
        # Ignore empty report
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-dockerfile-results.sarif
          category: CM/Dockerfile

      - name: CM Helm scan
        uses: bridgecrewio/checkov-action@v12
        with:
          config_file: checkov-helm.yaml
          output_format: cli,sarif
          output_file_path: console,checkov-helm-results.sarif

      - name: Upload CM Helm scan results to GitHub Security tab
        if: ${{ always() }}
        # Ignore empty report
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-helm-results.sarif
          category: CM/Helm
