name: Security scans on SCM
run-name: CI job triggered by ${{ github.event_name }} on ${{ github.ref_name }}
on:
  workflow_call:

jobs:
  security_scans_scm:
    runs-on: ubuntu-latest
    steps:
      - name: SCA scan (nodejs packages)
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"
      - run: npm ci
      - run: ./node_modules/.bin/retire -v

      - name: Run secrets-leak scan
        uses: trufflesecurity/trufflehog@v3.66.3
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --only-verified

      - name: SAST scan
        uses: bearer/bearer-action@v2
        id: sast
        with:
          format: sarif
          output: bearer-results.sarif

      - name: Upload SAST scan results to GitHub Security tab
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bearer-results.sarif
          category: SAST
