name: Security scans on container
run-name: SSC job triggered by ${{ github.event_name }} on ${{ github.ref_name }}
on:
  workflow_call:
    inputs:
      pull_image_from_registry:
        description: 'Pull image from registry before scan'
        default: false
        required: true
        type: boolean
      image_tag:
        description: 'An image tag to be scanned'
        default: 'v1.0.0'
        required: true
        type: string
    outputs:
      image_tag:
        description: "Output with image tag that was scanned"
        value: ${{ jobs.security_scans_container.outputs.image_tag }}

jobs:
  security_scans_container:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.customvars.outputs.image_tag }}
    steps:
      - name: Expose variable with image tag
        id: customvars
        run: echo "image_tag=${{ inputs.image_tag }}" >> $GITHUB_OUTPUT

      - name: Login to Azure Container Registry
        if: ${{ inputs.pull_image }}
        uses: azure/docker-login@v1
        with:
          # Global variable in GH
          login-server: ${{ vars.ACR_ADDRESS }}
          # Secrets in GH
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASS }}

      - name: Pull image from Azure Container Registry
        if: ${{ inputs.pull_image_from_registry }}
        run: |
          docker pull ${{ vars.ACR_ADDRESS }}/nodejs-colorizedapp:${{ inputs.image_tag }}

      - name: Download docker image stored as artifact
        if: ${{ ! inputs.pull_image_from_registry }}
        uses: actions/download-artifact@v3
        with:
          name: nodejs-colorizedapp_${{ inputs.image_tag }}
          path: /tmp

      - name: Load image
        if: ${{ ! inputs.pull_image_from_registry }}
        run: |
          docker load --input /tmp/nodejs-colorizedapp_${{ inputs.image_tag }}.tar

      - name: SCA Scan (docker image)
        uses: aquasecurity/trivy-action@master
        # Temporary because of security issues
        continue-on-error: true
        with:
          image-ref: '${{ vars.ACR_ADDRESS }}/nodejs-colorizedapp:${{ inputs.image_tag }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          scanners: 'vuln,secret,config'

      - name: Upload SCA scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ always() }}
        with:
          sarif_file: 'trivy-results.sarif'
          category: SCA
